import { loadTheme } from '@uifabric/styling';

export const lightTheme = () => loadTheme({
   palette: {
     themePrimary: '#125a97',
     themeLighterAlt: '#f2f7fb',
     themeLighter: '#cddfee',
     themeLight: '#a5c4e0',
     themeTertiary: '#5b91c0',
     themeSecondary: '#2568a3',
     themeDarkAlt: '#105087',
     themeDark: '#0e4372',
     themeDarker: '#0a3254',
     neutralLighterAlt: '#eeecec',
     neutralLighter: '#eae8e8',
     neutralLight: '#e1dede',
     neutralQuaternaryAlt: '#d1cfcf',
     neutralQuaternary: '#c8c6c6',
     neutralTertiaryAlt: '#c0bebe',
     neutralTertiary: '#a19f9d',
     neutralSecondary: '#605e5c',
     neutralPrimaryAlt: '#3b3a39',
     neutralPrimary: '#323130',
     neutralDark: '#201f1e',
     black: '#000000',
     white: '#f5f2f2',
   }});